### ISSUE TITLE
At least a surface level explanation of how things work?

### ISSUE THREAD

**Issue by Wyrmlet** [Argent-Matter/gcys#32]
### Feature Description

The mod is not exactly possible to properly test without any documentation, and the rest of the internet has nothing on it either. Some kind of basic guide on how to use any of this would be incredibly useful.

**Comment by zVoltaic** [comment]
VERY short explanation:

make a rocket scanner (check jei and make the multiblock **IN THE WEST/EAST DIRECTION**, cant make it in north/south yet because of a bug)

when building a rocket, you need to have a proper weight-thrust balance which you can check in the menu when you shift right click/open your inventory while sitting on a scanned rocket.

to make a rocket, you need rocket motors, fuel tanks, a seat(not required but you cant get on a rocket without one) and blocks for decoration if you want them

put the rocket motors at the bottom and fuel tanks above them. seats and decoration blocks go anywhere

each motor gives you 1m/s thrust and each fuel tank holds 5 buckets of fuel (as of now its the fuel tanks themselves that add to the weight, not the fuel inside them)

![image](https://github.com/Argent-Matter/gcyr/assets/153978270/f4c1cdbc-4372-4bee-bf9f-33dfba111a56)

this is an image of a simple rocket without decoration blocks (theres a 5th motor under the tanks)

once youve built a rocket, open the rocket scanner and click on the text that says "Scan Rocket". this will construct your rocket and make it interactable.

![image](https://github.com/Argent-Matter/gcyr/assets/153978270/5c8a1965-d8f4-4b60-84ec-371c33136203)

shift right click/sit on the rocket and open your inventory to check the thrust (you can only launch if its positive) and your fuel.

![image](https://github.com/Argent-Matter/gcyr/assets/153978270/805a2c84-540d-4b0a-8d88-e32d96332610)

click on the column on the left end with a fluid container holding rocket fuel to put fuel in your rocket (same way youd put fluids in any other gt machine)

to set your destination, craft a Magnet-strip Identification Chip (dont forget the hyphen) and on the left side of the screen, select the place you want to go to. once you do, it will automatically close the menu. the selected destination will show up sort of like a tooltip under the item's name. open the rocket's interface and put the chip in the middle slot

![image](https://github.com/Argent-Matter/gcyr/assets/153978270/c412dfda-b81c-41f4-8f26-50c9ace92531)

and thats all you have to do for building a rocket. sit on the rocket, open the gui and press launch to take off. once you reach the destination planet, hold space a decent amount of time before you hit the ground to not explode your rocket. trust me the acceleration is INSANE so you cant hold space at the last minute. will expand on this more when the mod's complete and space stations have been properly implemented
